spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.111.131:1433;databaseName=gcgl;
    username: SA
    password: xwsssyea1009.
    hikari:
      connection-test-query: SELECT 1
calcifer:
  weight:
    slave-ip: 10.206.4.243
    coil-num: 6
    enable-auth: false
    enable-auto-scan: false
    enable-modbus-device-init: false
    enable-serial-device-init: false
    enable-voice: false
    plate-reader-address: 192.168.1.100, 192.168.1.100
    # 控制modbus设备的时间间隔
    modbus-control-sleep-time: 100
    # 称重时的采样次数
    sampled-time: 10
    min-weight: 1000
    max-weight: 100000
    # 等待时间，单位毫秒，超过该时间没有状态变化将重置系统
    wait-time: 60000
    modbus-device-info-path: classpath:config/modbus_device_info.json
    serial-device-info-path: classpath:config/serial_device_info.json
    print-template: classpath:config/report.jasper
    #不带出门证
    print-template2: classpath:config/report2.jasper
    index-menu: classpath:config/index_menu.json

logging:
  config: classpath:config/logback-spring.xml
